# Generated by Django 3.1.4 on 2021-04-18 17:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelFlatSurface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='modelPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48Point', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('macPoint', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('color', models.TextField()),
                ('pixal_xy', models.TextField()),
                ('height', models.FloatField()),
                ('world_pixal_xy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='modelUserMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modelHexas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('wsg48center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('maccenter', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.modelusermarker')),
            ],
        ),
        migrations.CreateModel(
            name='modelHexaGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('wsg48center', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('mac48center', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.cities')),
            ],
        ),
        migrations.CreateModel(
            name='modelFOV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('angel', models.FloatField(default=45)),
                ('height', models.FloatField()),
                ('flatSurface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.modelflatsurface')),
            ],
        ),
        migrations.AddField(
            model_name='modelflatsurface',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.modelusermarker'),
        ),
    ]
