# Generated by Django 3.1.4 on 2021-03-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='modelPoint',
        ),
        migrations.RenameModel(
            old_name='Tiles',
            new_name='modelTiles',
        ),
    ]
