# Generated by Django 3.1.4 on 2021-03-06 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_buildingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelHexaGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('wsg48center', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('mac48center', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.cities')),
            ],
        ),
    ]
