# Generated by Django 3.1.4 on 2021-03-07 14:39

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0005_cities_modelhexagrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelFlatSurface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='modelUserMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modelFOV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('angel', models.FloatField(default=45)),
                ('height', models.FloatField()),
                ('flatSurface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.modelflatsurface')),
            ],
        ),
        migrations.AddField(
            model_name='modelflatsurface',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.modelusermarker'),
        ),
    ]
