# Generated by Django 3.1.4 on 2021-03-07 16:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20210307_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelHexas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsg48polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('macpolygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.modelusermarker')),
            ],
        ),
    ]
