# Generated by Django 3.1.4 on 2021-03-07 16:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_modelhexas'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelhexas',
            name='maccenter',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='modelhexas',
            name='wsg48center',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='modelhexas',
            name='macpolygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='modelhexas',
            name='wsg48polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
